// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/PRSV-Hackathon-2025/go-backend/internal/controller"
)

// Injectors from wire.go:

func InitializeHelloController() (*controller.HelloController, error) {
	helloController := controller.NewHelloController()
	return helloController, nil
}
