server:
  port: 8002
  mode: "local"
logger:
  logLevel: debug
  fileLogName: "./storages/logs/dev.log"
  MaxSize: 500
  MaxBackups: 3
  MaxAge: 28
  Compress: true
redis:
  addr: 127.0.0.1:6379
  password: ""
  db: 0
  poolSize: 10
