version: '3.9'
services:
  redis:
    image: redis:7.0
    container_name: redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8002:8002"
    depends_on:
      - redis
    volumes:
      - .:/app
    environment:
      - GO_ENV=local
    restart: unless-stopped

volumes:
  redis_data: